version: "3.4"

services:
  tinyified:
    container_name: megfolio 
    image: megfolio:latest
    ports:
      - 6969:80
    build:
      dockerfile: ./Dockerfile
    networks:
      - app

networks:
  app:

volumes:
  build:
